### ISSUE TITLE
Should be able to grant roles to users i.e. add entitlements

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/API-Manager#1]
Initially requested by @simonredfern 

We need to support add,remove and get entitlements.

https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#2_0_0-addEntitlement

https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#2_0_0-deleteEntitlement

https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#2_0_0-getEntitlements

This would be part of the Users tab

**Comment by sebtesobe** [comment]
Currently blocked by https://github.com/OpenBankProject/OBP-API/issues/233

**Comment by sebtesobe** [comment]
Has been deployed to https://apimanagersandbox.openbankproject.com . Please have a look.

**Comment by simonredfern** [comment]
Good Start, closing
