### ISSUE TITLE
Improvements to User search field / button.

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Manager#33]
Search for Users button doesn't seem to work (Firefox Mac)
Have to hit enter key for search to work.
Also buttton should be to the right (not left) of search box
Also field text button says we have to enter email address - but username works as well.

**Comment by sebtesobe** [comment]
The button did not work because it was no button. Now it is and i moved it to the right of the input field.
See https://apimanagersandbox.openbankproject.com/users/

Can you give an example where username works and it does _not_ coincide with parts of the email address?
