### ISSUE TITLE
Add Entitlement Requests tab

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Manager#38]
Add page to list Entitlement Requests.

Each row will contain

Username (includes link to User), Email, Role Requested. Accept Button, Reject Button.

When Accept Button is pressed:
1) Role Entitlment is created.
2) Entitlment Request status is set to GRANTED.

When Reject button is pressed
1) 2) Entitlment Request status is set to REJECTED.

**Comment by constantine2nd** [comment]
@simonredfern Ready for testing.
