### ISSUE TITLE
consumers gives 500 error

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Manager#8]
Is this due to recent change in consumers json?

**Comment by hongwei1** [comment]
@simonredfern  Yes, It is the Json Format .you can assign the ticket to me . I can fix it in API-Manager

**Comment by simonredfern** [comment]
was due to API changing field names (draft version)

**Comment by sebtesobe** [comment]
I wonder if the API Manager should be less optimistic about these field names and become more defensive, e.g. by implementing something like #4 .
